In [1]:
!pip install yfinance

Collecting yfinance
  Using cached yfinance-1.2.2-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pandas>=1.3.0 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from yfinance) (3.0.2)
Requirement already satisfied: numpy>=1.16.5 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from yfinance) (2.4.4)
Requirement already satisfied: requests>=2.31 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from yfinance) (2.33.1)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.12-py3-none-any.whl
Requirement already satisfied: platformdirs>=2.0.0 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from yfinance) (4.9.6)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.7-py3-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Using cached peewee-4.0.4-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from yfinance) (4.14.3)
Collecting curl_cffi>=0.15 (from yfinance)
  Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Using cached websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>=1.6.1 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.2.25)
Collecting rich (from curl_cffi>=0.15->yfinance)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pycparser in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2026.1)
Requirement already satisfied: six>=1.5 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Collecting markdown-it-py>=2.2.0 (from rich->curl_cffi>=0.15->yfinance)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\stock_selection_and_portfolio_optimization_system_for_pure_equity_mutual_funds\.venv\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached yfinance-1.2.2-py2.py3-none-any.whl (130 kB)
Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
Downloading frozendict-2.4.7-py3-none-any.whl (16 kB)
Using cached peewee-4.0.4-py3-none-any.whl (144 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, protobuf, mdurl, frozendict, markdown-it-py, rich, curl_cffi, yfinance

   ----------------------------------------  0/11 [pytz]
   --- ------------------------------------  1/11 [peewee]
   ---------- -----------------------------  3/11 [websockets]
   -------------- -------------------------  4/11 [protobuf]
   ------------------------- --------------  7/11 [markdown-it-py]
   ----------------------------- ----------  8/11 [rich]
   ----------------------------- ----------  8/11 [rich]
   -------------------------------- -------  9/11 [curl_cffi]
   ------------------------------------ --- 10/11 [yfinance]
   ---------------------------------------- 11/11 [yfinance]

Successfully installed curl_cffi-0.15.0 frozendict-2.4.7 markdown-it-py-4.0.0 mdurl-0.1.2 multitasking-0.0.12 peewee-4.0.4 protobuf-7.34.1 pytz-2026.1.post1 rich-15.0.0 websockets-16.0 yfinance-1.2.2

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import yfinance as yf

def get_trading_api(stock):
    df = yf.download(stock, period="5y", interval="1d")
    df.reset_index(inplace=True)
    df['Stock'] = stock
    return df

In [12]:
get_trading_api("TCS.NS")

[*********************100%***********************]  1 of 1 completed

Price,Date,Close,High,Low,Open,Volume,Stock
Ticker,,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,
0,2021-04-13,2728.698975,2825.353447,2701.447588,2825.353447,8654596,TCS.NS
1,2021-04-15,2829.704834,2845.791986,2714.106210,2778.147054,6062760,TCS.NS
2,2021-04-16,2808.782471,2854.362694,2797.750227,2838.539310,3224657,TCS.NS
3,2021-04-19,2779.466064,2803.376919,2755.994748,2785.795377,2679106,TCS.NS
4,2021-04-20,2764.301270,2835.330725,2748.302113,2835.022962,3141893,TCS.NS
...,...,...,...,...,...,...,...
1231,2026-04-07,2539.800049,2543.899902,2448.000000,2461.000000,4516550,TCS.NS
1232,2026-04-08,2559.199951,2580.300049,2540.100098,2572.000000,4769337,TCS.NS
1233,2026-04-09,2589.000000,2605.000000,2531.100098,2554.000000,5628261,TCS.NS
1234,2026-04-10,2524.300049,2565.800049,2501.100098,2565.800049,10480239,TCS.NS
1235,2026-04-13,2472.600098,2504.899902,2470.000000,2489.899902,3739587,TCS.NS

In [4]:
import yfinance as yf

# data = yf.download("TCS.NS", start="2026-04-06", end="2026-04-14", interval="1m")
market =  yf.download("^NSEI", period="1d",interval="1m")
print(market.head())

[*********************100%***********************]  1 of 1 completed

Price                             Close          High           Low  \
Ticker                            ^NSEI         ^NSEI         ^NSEI
Datetime
2026-04-17 03:45:00+00:00  24177.800781  24177.800781  24109.449219
2026-04-17 03:46:00+00:00  24148.750000  24222.199219  24143.150391
2026-04-17 03:47:00+00:00  24205.599609  24210.800781  24150.900391
2026-04-17 03:48:00+00:00  24212.750000  24222.599609  24204.650391
2026-04-17 03:49:00+00:00  24207.550781  24218.949219  24197.050781

Price                              Open Volume
Ticker                            ^NSEI  ^NSEI
Datetime
2026-04-17 03:45:00+00:00  24173.599609      0
2026-04-17 03:46:00+00:00  24179.099609      0
2026-04-17 03:47:00+00:00  24150.900391      0
2026-04-17 03:48:00+00:00  24205.800781      0
2026-04-17 03:49:00+00:00  24215.000000      0

In [5]:
market['Close'].pct_change()

Ticker                        ^NSEI
Datetime
2026-04-17 03:45:00+00:00       NaN
2026-04-17 03:46:00+00:00 -0.001202
2026-04-17 03:47:00+00:00  0.002354
2026-04-17 03:48:00+00:00  0.000295
2026-04-17 03:49:00+00:00 -0.000215
...                             ...
2026-04-17 09:55:00+00:00 -0.000215
2026-04-17 09:56:00+00:00  0.000019
2026-04-17 09:57:00+00:00 -0.000010
2026-04-17 09:58:00+00:00  0.000045
2026-04-17 09:59:00+00:00  0.000150

[375 rows x 1 columns]